name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    PRIMARY_NODEJS_VERSION: 24.x

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
            - run: npm ci
            - run: npm run lint

    test-bundle:
        name: Test bundle
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
            - run: npm ci
            - run: npm run bundle-and-test -- -- --reporter min

    unit-tests:
        name: Unit tests
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [25.x, 24.x, 22.x, 20.x, "20.19.0"]
                include:
                    - os: windows-latest
                      node: "lts/*"
                    - os: macOS-latest
                      node: "lts/*"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node }}
            - run: npm ci
            - run: npm run test -- --reporter min
            - run: npm run esm-to-cjs-and-test -- -- --reporter min
            - run: npm run coverage
              if: ${{ matrix.node == env.PRIMARY_NODEJS_VERSION }}
            - name: Coveralls parallel
              if: ${{ matrix.node == env.PRIMARY_NODEJS_VERSION }}
              uses: coverallsapp/github-action@1.1.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                flag-name: node-${{ matrix.node }}
                parallel: true

    test_types:
        name: Test Types
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - name: Install dependencies
              run: npm install
            - name: Check Types
              run: npm run test:types

    send-to-coveralls:
        name: Send coverage to Coveralls
        needs: unit-tests
        runs-on: ubuntu-latest
        steps:
            - name: Send coverage to Coveralls
              uses: coverallsapp/github-action@1.1.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                parallel-finished: true
