name: update-mdn-data

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
    update-mdn-data:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: npm install

            - name: Update mdn-data
              run: npm install mdn-data@latest --save-exact

            - name: Remove redundant syntax patches
              run: npm run review:syntax-patch

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
              with:
                  token: ${{ secrets.WORKFLOW_PUSH_BOT_TOKEN }}
                  commit-message: "fix: update mdn-data"
                  title: "fix: update mdn-data"
                  branch: update-mdn-data
                  branch-suffix: timestamp
                  body: |
                      - Updated `mdn-data` to the latest version.
                      - Ran `npm run review:syntax-patch` to remove redundant syntax patches.
                      
                      This PR is autogenerated by the "update-mdn-data" GitHub Action.
